site_name: ''
site_url: https://businessanalyticscentre.website/
site_description: Democratising Analytics, Increasing Collaborations, Industry Focused
site_author: TBAC Team

theme:
    name: mkdocs
    logo: img/logo-white.png
    locale: en
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Roadmap: roadmap.md
    - Team:
        - Overview: team.md
        - Associate Professor Nik Thompson: "https://staffportal.curtin.edu.au/staff/profile/view/nik-thompson-d7141bdd/"
        - Dr Luke Butcher: "https://staffportal.curtin.edu.au/staff/profile/view/luke-butcher-dc35ec50/"
        - Dr Michael Borck: "https://staffportal.curtin.edu.au/staff/profile/view/Michael.Borck/"
    - Showcase:
        - Overview: showcase/index.md
        - Blackboard Discussion: showcase/discussion-board/discussion-board.md
        - Brand Analytics: showcase/brand-analytics/brand-analytics.md
        - Customer Churn:
            - CRISP-DM Overview: showcase/customer-churn/00_crisp-dm/00_crisp-dm.md
            - Business Understanding: showcase/customer-churn/01_business-understanding/01_business-understanding.md
            - Data Understanding: showcase/customer-churn/02_data-understanding/02_data-understanding.md
            - Data Preparation: showcase/customer-churn/03_data-preparation/03_data-preparation.md
            - Modeling: showcase/customer-churn/04_modeling/04_modeling.md
            - Evaluation: showcase/customer-churn/05_evaluation/05_evaluation.md
            - Deployment: showcase/customer-churn/06_deployment/06_deployment.md
        - Visual Decisions: showcase/visual-decisions/visual-decisions.md
        - Automated PCA: showcase/pca-analysis/pca-analysis.md

    - Contact:
        - A.Prof Nik Thompson: "mailto:nik.thompson@curtin.edu.au?subject=Discuss%20Business%20Analytics"
        - Dr Luke Butcher: "mailto:luke.butcher@curtin.edu.au?subject=Discuss%20Business%20Analytics"
        - Dr Michael Borck: "mailto:michael.borck@curtin.edu.au?subject=Discuss%20Business%20Analytics"

extra:
  analytics:
    provider: google
    property: G-XY97PKGBWT

extra_css:
    - css/extra.css

plugins:
    - search
