site_name: ''
site_url: https://businessanalyticscentre.website/
site_description: Democratising Analytics, Increasing Collaborations, Industry Focused
site_author: TBAC Team


theme:
    name: mkdocs
    logo: img/logo-white.png
    locale: en
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Roadmap: roadmap.md
    - Team:
        - Overview: team.md
        - Associate Professor Nik Thompson: "https://staffportal.curtin.edu.au/staff/profile/view/nik-thompson-d7141bdd/"
        - Dr Luke Butcher: "https://staffportal.curtin.edu.au/staff/profile/view/luke-butcher-dc35ec50/"
        - Dr Michael Borck: "https://staffportal.curtin.edu.au/staff/profile/view/Michael.Borck/"
    - Showcase:
        - Overview: show-case/index.md
        - Brand Analytics: show-case/brand-analytics.md
        - Customer Churn: show-case/customer-churn.md
        - Employee Retention: show-case/employee-retention.md
        - Inventory Management: show-case/inventory-management.md
        - Sales Forecast: show-case/sales-forecast.md


extra_css:
    - css/extra.css

plugins:
    - search
